config/routes.rb
SongMoments::Application.routes.draw do

root "moments#index"

get "about" => "moments#about"

get "how_it_works" => "moments#how_it_works"

get "moments" => "moments#moments"

resources :moments

devise_for :users

resources :users

resources :moments do
    resources :comments
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :moment
end

app/models/moment.rb
class Moment < ActiveRecord::Base

	validates :title, :image, :blog, :song, :presence => true

	belongs_to :user

	has_many :comments

	belongs_to :sound

 	mount_uploader :image, ImageUploader

 	before_save :fill_song_url


  def fill_song_url

    # title = URI::encode(self.title)
    # omdb_json = RestClient.get("http://www.omdbapi.com/?i=&t=#{title}")
    # omdb_movie = JSON.load(omdb_json)
    # self.poster = omdb_movie["Poster"]

    title = self.song
    client = Soundcloud.new(:client_id => '8e38e03320f1b0cdde7d69fe832142c9')
	tracks = client.get('/tracks', :q => title ,:limit => 1)
	
	if tracks.length != 0 

		self.song_url = tracks[0].uri

	end

  end

 

end

app/models/picture.rb
class Picture < ActiveRecord::Base

	belongs_to :moment

	has_attached_file :picture,
					  :styles => {
					  		:medium => "250x250>",	
					  		:thumb  => "80x80>"
					  }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :moments

  has_many :comments

  after_create :send_welcome_email

  def send_welcome_email
  	UserMailer.welcome_email(self).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 before_action :authenticate_user!, :only => [:create]

	def create

		@moment = Moment.find(params[:moment_id])

		safe_comment = params.require(:comment).permit(:text)

		@comment = Comment.new(safe_comment)
		@comment.moment = @moment
		@comment.user = current_user
		@comment.save

		redirect_to @comment.moment

	end
	

	def destroy

		@moments = Comment.find(params[:moment_id])	# Destroys a shirt

		@moments.destroy

		redirect_to moments_path

	end

end

app/controllers/main_controller.rb
class MainController < ApplicationController

	def index

		@moments = Moment.all

	end

	def about

	end

	def how_it_works

	end

	def moments

		@moments = Moment.all

	end

	def show

		@moment = Moment.find( params[:id])

	end

end

app/controllers/moments_controller.rb
class MomentsController < ApplicationController


 before_action :authenticate_user!, :only => [:new, :create, :moments, :image]


	def index

		@moments = Moment.all

	end

	def about

	end

	def how_it_works

	end

	def moments

		@moments = Moment.all.order("created_at DESC")

		@client = Soundcloud.new(:client_id => '8e38e03320f1b0cdde7d69fe832142c9')

		# get a tracks oembed data
		
	end

	def show

		@moment = Moment.find(params[:id])
		@comment = Comment.new
		@client = Soundcloud.new(:client_id => '8e38e03320f1b0cdde7d69fe832142c9')


	end


	def new

		@moment = Moment.new

	end

	def create

		@moment = Moment.new(safe_moment_params)

		@moment.user = current_user
		
		if @moment.save

			redirect_to moments_path

		else 

			render :new

		end

	end


	def edit									# Edits a shirt

		@moment = Moment.find(params[:id])

	end


	def update

		@moment = Moment.find(params[:id])

		@moment.update(safe_moment_params)    # Saves the object so you don't have to call @shirt.save

		redirect_to moments_path(@moment)

	end

	def destroy

		@moment = Moment.find(params[:id])	# Destroys a shirt

		@comments = @moment.comments.all

		@comments.each do |comment|

			comment.destroy
		end

		@moment.destroy

		# Get all the comments for that specific moment and destroy them all

		redirect_to moments_path

	end


	private

	def safe_moment_params

		return params.require(:moment).permit(:title, :image, :blog, :song)

	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def show

		@user = User.find(params[:id])
		@client = Soundcloud.new(:client_id => '8e38e03320f1b0cdde7d69fe832142c9')

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/moments_helper.rb
module MomentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoteworthyMoments</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Stalemate' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
</head>

<body>

<%= bootstrap_flash %>

	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <a class="brand" href="<%= root_path %>"><span>Noteworthy Moments</span></a>
	   		  <ul class="nav">
                <li 
                    <% if params[:controller] == "main" and params[:action] == "about" %> 
                    class="active"
                    <% end %>
                >
                    <a href="<%= about_path %>">About</a>
                </li>
                <li
                    <% if params[:controller] == "main" and params[:action] == "how_it_works" %> 
                    class="active"
                    <% end %>
                >
                    <a href="<%= how_it_works_path %>">How it Works</a>
                </li>
                <li
                    <% if params[:controller] == "main" and params[:action] == "moments" %> 
                    class="active"
                    <% end %>
                >
                    <a href="<%= moments_path %>">Moments</a>
                </li>
                <li
                    <% if params[:controller] == "main" and params[:action] == "add_moment" %> 
                    class="active"
                    <% end %>
                >
                    <a href="<%= new_moment_path %>">Add Moment</a>
                </li>

            </ul>

          <div style="float:right;">
            <ul>
              <li>
              <% if user_signed_in? %>
                <%= current_user.email %>
                <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
              <% else %>

                <a class="btn btn-danger" href="<%= new_user_session_path %>">Log In</a> |
                <a class="btn btn-danger" href="<%= new_user_registration_path %>">Sign Up</a>

              <% end %>
              <li>
            </ul>
          </div>
	  </div>
	</div>

		<%= yield %>
		

</body>
</html>

app/views/main/about.html.erb
 <div class="container">
	<h1 style="text-align:center;"> About </h1>

	<br>

		<p class="lead">
			My goal is to provide people with the ability to design a personal library of music that becomes a playlist of nostalgia.
		</p>
</div>

 <img src="<%= image_path("guitar.jpg") %>" >

<div class="container">

	<div class="row">

		<ul class="features features-list1 clearfix unstyled">

			<li class="span6" style="text-align:center;">
				<div class="icons">
					<i class="icon-music"></i>
				</div>

				<div class="content">
						<h2>Save Your Songs</h2>
						<p class="lead"> 
							As humans we gravitate towards music because it can move our emotions and captivates our feelings in a way that science can't capture. Save it. 
						</p>
					</div>
			</li>

			<li class="span6" style="text-align:center;">
				<div class="icons">
					<i class="icon-play"></i>
				</div>

				<div class="content">
						<h2>Design Your Own Playlist</h2>
						<p class="lead">
							As your music library grows, you can listen to an entire playlist that consists of all the songs that generate flashbacks from your past. 
						</p>
					</div>
			</li>

			<li class="span6" style="text-align:center;">
				<div class="icons">
					<i class="icon-heart"></i>
				</div>

				<div class="content">
						<h2>Share Your Music</h2>
						<p class="lead">
							Let others into your sonic world by sharing your playlist with them. Who knows? Maybe people will share the experiences that you have had. 
						</p>
					</div>
			</li>

			<li class="span6" style="text-align:center;">
				<div class="icons">
					<i class="icon-camera"></i>
				</div>

				<div class="content">
						<h2>Add Images to Your Moments</h2>
						<p class="lead"> 
							If you have pictures of the place that you experienced the moment, you can also add them to your library!
						</p>
					</div>
			</li>



		</ul>	





	</div>	


</div>

app/views/main/how_it_works.html.erb
s
<div class="container">
	<h1 style="text-align:center;"> How It Works </h1>
</div>

<div class="hero-unit" style="margin-top: 10px; background-color:#DBF2FC;">
		<div class ="container-fluid">
			<div class="row-fluid">
				<div class="span6" style="margin:auto 0">

					<h1>Upload Songs</h1>

				</div>
				<div class="span6">

					<img src="<%= image_path("place_holder.png") %>" >


				</div>
			</div>
		</div>
	</div>

	<div class="hero-unit" style="background-color:white; margin-top: -30px;">
		<div class ="container-fluid">
			<div class="row-fluid">
				<div class="span6">

					<img src="<%= image_path("place_holder.png") %>" >

				</div>
				<div class="span6" style="margin:auto 0">

					<h1>Write a Blog Post</h1>

				</div>
			</div>
		</div>
	</div>

		<div class="hero-unit" style="margin-top: -30px; background-color: #DBF2FC;">
		<div class ="container-fluid">
			<div class="row-fluid">
				<div class="span6" style="margin:auto 0">

					<h1>Post an Image</h1>

				</div>
				<div class="span6">

					<img src="<%= image_path("place_holder.png") %>" >


				</div>
			</div>
		</div>
	</div>

	<div class="hero-unit" style="background-color:white; margin-top: -30px;">
		<div class ="container-fluid">
			<div class="row-fluid">
				<div class="span6">

					<img src="<%= image_path("place_holder.png") %>" >

				</div>
				<div class="span6" style="margin:auto 0">

					<h1>Share with Friends</h1>

				</div>
			</div>
		</div>
	</div>

app/views/main/index.html.erb
	<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
    	    		<img src="<%= image_path("music_everything.jpg") %>" >
<!-- 
    		<div class="carousel-caption">
    			<h4> Noteworthy Moments </h4>
    		</div> -->
    </div>
    <div class="item">	<img src="<%= image_path("music_everything.jpg") %>" ></div>
    <div class="item">	<img src="<%= image_path("music_everything.jpg") %>" ></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>


	<div class="hero-unit" style="margin-top: -30px;">
		<div class ="container-fluid">
			<div class="row-fluid">
				<div class="span6">

					<img src="<%= image_path("place_holder.png") %>" >

				</div>
				<div class="span6" style="margin:auto 0">

					<h1 style="margin-bottom:8px;">Note your worthy moments</h1>
					<p>Music has always been an integral part of our lives. It can serve as a time machine that sends us back to specific moments in time. Why not collect it?</p>
					<p>
		    		<a class="btn btn-primary btn-large">Get Started</a>
		  			</p>

				</div>
			</div>
		</div>
	</div>

	

app/views/main/moments.html.erb
<div class="container" style="text-align:center;">

<h1> My Moments </h1>

<p> Coming Soon...</p>

</div>

app/views/moments/_form.html.erb
<div style="text-align:center;">

<% if @moment.errors.any? %>
    <h2>There were errors saving your moment</h2>
	   <ul>
	     <% @moment.errors.full_messages.each do |msg| %>
	       <li><%= msg %></li>
	     <% end %>
	   </ul>
<% end %>

</div>

<%= form_for @moment, :html => { :class => "formclass" } do |f| %>

	<div>
		<%= f.label :title, "Title:", :class =>"label-class" %><br>
		<%= f.text_field :title %>
	</div>

	<div>
		<%= f.label :song, "Song:" %><br>
		<%= f.text_field :song %>
	</div>

	<div>
		<%= f.label :blog, "Description:" %><br>
		<%= f.text_area :blog %>
	</div>


	<div>
	<%= f.label :image  %>	
	<%= f.file_field :image %>
	</div>

	<br>
	<%= f.submit "Create Moment", :class =>"btn btn-danger" %>

<% end %>


	

app/views/moments/about.html.erb
 <div class="container">
	<h1 style="text-align:center;"> About </h1>

	<br>

	<p class="lead">
		My goal is to provide people with the ability to design a personal library of music that becomes a playlist of nostalgia.
	</p>
</div>

<img src="<%= image_path("guitar.jpg") %>" >

<div class="container">

	<div class="row">

		<ul class="features features-list1 clearfix unstyled">

			<li class="span6" style="text-align:center;">
				<div class="icons">
					<i class="icon-music"></i>
				</div>

				<div class="content">
						<h2>Save Your Songs</h2>
						<p class="lead"> 
							As humans we gravitate towards music because it can move our emotions and captivates our feelings in a way that science can't capture. Save it. 
						</p>
					</div>
			</li>

			<li class="span6" style="text-align:center;">
				<div class="icons">
					<i class="icon-play"></i>
				</div>

				<div class="content">
						<h2>Design Your Own Playlist</h2>
						<p class="lead">
							As your music library grows, you can listen to an entire playlist that consists of all the songs that generate flashbacks from your past. 
						</p>
					</div>
			</li>

			<li class="span6" style="text-align:center;">
				<div class="icons">
					<i class="icon-heart"></i>
				</div>

				<div class="content">
						<h2>Share Your Music</h2>
						<p class="lead">
							Let others into your sonic world by sharing your playlist with them. Who knows? Maybe people will share the experiences that you have had. 
						</p>
					</div>
			</li>

			<li class="span6" style="text-align:center;">
				<div class="icons">
					<i class="icon-camera"></i>
				</div>

				<div class="content">
						<h2>Add Images to Your Moments</h2>
						<p class="lead"> 
							If you have pictures of the place that you experienced the moment, you can also add them to your library!
						</p>
				</div>
			</li>
		</ul>	
	</div>	
</div>

app/views/moments/edit.html.erb
<div class="container">

	<h1 style="text-align:center;"> Editing a Moment </h1>

	<%= render "moments/form" %>

</div>

app/views/moments/how_it_works.html.erb
<div class="container "style="text-align:center;">
	<h1> How It Works </h1>
	<br>
	<p class="lead"> Follow these four simple steps!</p>
</div>

 <img src="<%= image_path("piano.jpg") %>" >

	<div class="hero-unit" style="margin-top: -10px; background-color:#f2f2f2;">
		<div class ="container">
			<div class ="container-fluid">
				<div class="row-fluid">

					<div class="span6">
						<div class="steps circle one">
								1
						</div>	
					</div>

					<div class="span6" >
						<h1>Title Your Moment</h1>
					</div>
				
				</div>
			</div>
		</div>
	</div>

	<div class="hero-unit" style="background-color:white; margin-top: -30px;">
		<div class="container">
			<div class ="container-fluid">
				<div class="row-fluid">

					<div class="span6">
						<div class="steps circle two">
								2
						</div>	
					</div>
					
					<div class="span6">
						<h1>Search for a Song</h1>
					</div>

				</div>
			</div>
		</div>
	</div>

	<div class="hero-unit" style="margin-top: -30px; background-color: #f2f2f2;">
		<div class="container">
			<div class ="container-fluid">
				<div class="row-fluid">

					<div class="span6">
						<div class="steps circle three">
								3
						</div>	
					</div>

					<div class="span6">
						<h1>Write a Description</h1>
					</div>
						
				</div>
			</div>
		</div>
	</div>

	<div class="hero-unit" style="background-color:#white; margin-top: -30px;">
		<div class="container">
			<div class ="container-fluid">
				<div class="row-fluid">

					<div class="span6">
						<div class="steps circle four">
								4
						</div>	
					</div>
					
					<div class="span6">
						<h1>Post an Image</h1>
					</div>

				
				</div>
			</div>
		</div>
	</div>

app/views/moments/index.html.erb
  <div class="hero-unit" style="margin-top: 35px; text-align:center;">
    <div class ="container-fluid">
      <div class="row-fluid">
      
        <div class="span12">
          <h1 style="margin-bottom:8px;">Note Your Worthy Moments</h1>
          <p class="lead">Create your own song library of precious moments and never lose them again</p>
          <p>
            <a class="btn btn-danger btn-large" href="<%= new_user_registration_path %>">Get Started</a>
            </p>
        </div>

      </div>
    </div>
  </div>

  <hr class="soften" style="margin-top: -60px;">

  <div class="container" style="margin-top:0px; margin-bottom:20px; text-align:center;">
    <div class="row">

      <div class="span4">
        <h2>Build Your Collection</h2>
        <p class="lead">
            Creating your own playlist is simple. Just upload your memorable songs straight to the website and access it from anywhere. 
        </p>
      </div>

      <div class="span4">
        <h2>Store Your Memories</h2>
        <p class="lead">
            Your life's events can be stored in a single place and whenever you want to take a walk down memory lane, you know where to go.
        </p>
      </div>

      <div class="span4">
        <h2>Share & Follow</h2>
        <p class="lead">
          Follow your friends and share your experiences together.
        </p>
      </div>
      
    </div>
  </div>
  
  <div id="myCarousel" class="carousel slide">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
    <!-- Carousel items -->
      <div class="carousel-inner">
        <div class="active item" >
        	    <img src="<%= image_path("girl_on_floor.jpg") %>" >
        </div>
        <div class="item">	<img src="<%= image_path("music_everything.jpg") %>" ></div>
        <div class="item">	<img src="<%= image_path("shirtless.jpg") %>" height = "810"></div>
      </div>
    <!-- Carousel nav -->
      <a class="carousel-control left" href="#myCarousel" data-slide="prev" >&lsaquo;</a>
      <a class="carousel-control right" href="#myCarousel" data-slide="next" >&rsaquo;</a>
  </div>

app/views/moments/moments.html.erb
<div class="container" style="text-align:center;">

  <h1> All Moments </h1>

  <a class="btn btn-danger btn-large" href="<%= new_moment_path %>">Add Moment</a>
     <div class="row">
      <div class="span3">
      </div>

     <div class="momentlist span6">
        <ul class="thumbnails">

          <% @moments.each do |moment| %>
             <li class="span6">

              <div class="title">
             	   <h2><a href="<%= moment_path(moment)%>"><%= moment.title %></a></h2>
              </div>

              <div class ="post">
                 <h4>
                    posted by <a href = "<%= user_path( moment.user ) %>"><%= moment.user.email %></a> <%= time_ago_in_words( moment.created_at ) %> ago
                </h4>
               </div> 

              <% if moment.image.present? %>
              <div>
                  <img src="<%= moment.image.url %>"/>
              </div>
              <% end %>

              <div class="blog">
                  <h4><%= moment.blog %></h4>
              </div> 

              <div class="song">
                 <h3><%= moment.song %></h3>
              </div>
                 <% if moment.song_url.present? %>
                    <%==  @client.get('/oembed', :url => moment.song_url)['html'] %>
                 <% else %>
                    <%= moment.song_url %>
                 <% end %>
              
              <h4><a href="<%= edit_moment_path( moment ) %>" class ="btn btn-inverse">Edit</a></h4>

              <% end %>
            </li>
          </ul>
        </div>
     </div>
</div>

app/views/moments/new.html.erb
<div class="container">

	<h1 style="text-align:center;"> Create a new moment </h1>

	<%= render "moments/form" %>

</div>

app/views/moments/show.html.erb
<div class="container" style="text-align:center;">

  <div class="title">
   	  <h1><%= @moment.title %></h1>
  </div>

  <% if @moment.image.present? %>
        <div>
            <img src="<%= @moment.image.url %>"/>
        </div>
  <% end %>
    <div class="blog">
      <h3><%= @moment.blog %></h3>
    </div> 

    <div class="song">
      <h3><%= @moment.song %></h3>
    </div>

    <% if @moment.song_url.present? %>
          <%==  @client.get('/oembed', :url => @moment.song_url)['html'] %>
    <% else %>
          <%= @moment.song_url %>
    <% end %>

    <div class="edit">
      <h4><a href="<%= edit_moment_path( @moment ) %>" class ="btn btn-inverse">Edit</a></h4>
    </div>

    <div class ="post">
       <h4>
         <p>posted by <a href = "<%= user_path( @moment.user ) %>"><%= @moment.user.email %></a><%= time_ago_in_words( @moment.created_at ) %> ago</p>
       </h4>
    </div>

  <br>

  <%= button_to "Delete Moment", moment_path(@moment), :method => :delete , class: "btn btn-danger btn-medium"%>


  <!-- Make it redirect to moments tab -->

  <h1>Comments</h1>

  <ul>
    <% @moment.comments.each do |comment| %>
      <li>
          <h3><%= comment.text %></h3>  
          <p>comment posted by <a href = "<%= user_path( comment.user ) %>"><%= comment.user.email %></a> <%= time_ago_in_words( comment.created_at ) %> ago</p>
      </li>

 
    <% end %>
  </ul>

  <%= form_for [@moment, @comment] do |f| %>
  <%= f.text_area :text, :placeholder => "Add a comment...", :rows => 8, :cols => 40 %>

  <br>

  <%= f.submit "Post Comment", :class =>"btn btn-danger"  %>

  <% end %>

</div>

app/views/users/show.html.erb
<div class="container" style="text-align:center;">

<h1><%= @user.email %></h1>


	<ul class="thumbnails">
		
		<% @user.moments.each do |moment| %>

			<li class="span12">
			    <h1><a href="<%= moment_path(moment)%>"><%= moment.title %></a></h1>

     		  	<% if moment.image.present? %>
       				<div>
       				    <img src="<%= moment.image.url %>"/>
     			    </div>
  				<% end %>	

    			<h4><%=  moment.blog %></h4>

     			<h3><%= moment.song %></h3>

     			 <% if moment.song_url.present? %>
                    <%==  @client.get('/oembed', :url => moment.song_url)['html'] %>
                 <% else %>
                    <%= moment.song_url %>
                 <% end %>

			    <p>
			        posted by <a href="<%= user_path( moment.user )%>"><%= moment.user.email %></a> <%= time_ago_in_words( moment.created_at ) %> ago
			    </p>
			</li>
		<% end %>   
	</ul>

</div>


<div class="container" style="text-align:center;">

  <h1>Comments</h1>
 
	<ul>
		<% @user.comments.each do |comment| %>
			<li>
				<p><%= link_to comment.moment.title, moment_path( comment.moment ) %> </p>
			    <p>comment posted by <%= link_to comment.user.email, user_path( comment.user ) %> <%= time_ago_in_words( comment.created_at ) %> ago</p>
			    <p><%= comment.text %></p>
			</li>
		<% end %>
	</ul>

</div>